graph LR
    subgraph Presentation Layer
        UI[Streamlit Web App]
    end
    subgraph Application Logic Layer
        HE[Heuristic Engine]
    end
    subgraph Data Layer
        DB[(SQLite DB)]
    end
    UI <--> HE
    HE <--> DB
